version: '3'

services:
  nats:
    container_name: queue-service
    entrypoint: '/nats-server -c nats-server.conf -DV'
    image: nats
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
  stories-database:
    container_name: stories-database
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="stories"
    ports:
      - '27017:27017'
